### ISSUE TITLE
Dealing with cameras with optical zoom.

### ISSUE THREAD

**Issue by jperrela** [Theta-Limited/camera-calibration#3]
Hi, 

I'm trying to calibrate a camera with a 30x optical zoom. 
Do you have any idea how to proceed in this case? I just take the pictures with 1x and use that results?

Best

**Comment by mkrupczak3** [comment]
Yes @jperrela, recommend taking pictures at 1x (or whatever is the minimum focal length).

The effect of lens distortion is usually incredibly small; my best understanding is that these parameters remain invariant anyways regardless of focal length

**Comment by mkrupczak3** [comment]
One caviot is that some drone gimbals (such as the Parrot Anafi) swap between different physical cameras for varying levels of zoom; These may be more tricky to calibrate and we don't have a well-defined procedure. The results should be decent regardless if all cameras use the same size CMOS sensor

**Comment by mkrupczak3** [comment]
Updated documentation instructions
